Adds GitHub Workflows support by deploying to AWS Lambda
ASE-FS24/post-manager pull request #2
Opened 2024-03-16 00:18 UTC by r-carissimi

2024-03-17 19:05 UTC, krwro requested changes

2024-03-17 19:05 UTC, krwro commented on .github/workflows/deploy-to-lambda.yml
> +          aws s3 cp target/usermanager.jar s3://$S3_BUCKET/$S3_KEY
postmanager?

2024-03-18 11:43 UTC, r-carissimi commented on .github/workflows/deploy-to-lambda.yml
> +          aws s3 cp target/usermanager.jar s3://$S3_BUCKET/$S3_KEY
yep, sorry
fixed the typo

2024-03-19 11:42 UTC, krwro approved these changes

2024-03-19 11:42 UTC, merged